### ISSUE TITLE
Build the queue

### ISSUE THREAD

**Issue by rtruo001** [rtruo001/AppleTea#12]
- [ ] Queue
  - [x] Initializes queue to the server's queue
  - [x] Prevents duplicates from being added to queue
  - [ ] Add the shuffle button
  - [ ] Add the like button in queue
  - [x] Display number of added media entries
  - [ ] Display total media entries added from a playlist
  - [ ] Update queue when media player requests next song
  - [x] Updates queue when dragging media entries and their positions
## 7/30/16
- Queue is currently draggable.
- Queue is updated in server whenever the queue is changed on the client side.
