### ISSUE TITLE
UI & UX Design (Task List)

### ISSUE THREAD

**Issue by gerardliu** [rtruo001/AppleTea#16]
Finish Entire UI & UX Design for the App:
- [ ] Home Page
  - [ ] Room Creator
  - [ ] Room List / Manager
  - [ ] Friend List / Manager
  - [ ] Your Profile (and Edit)
- [ ] Room Page
  - [ ] Header & User Nav
  - [x] Video Chat Banner
    - [ ] Video Plyr & Custom Btns/Styling
    - [x] Room Header & Mod Controls
    - [x] Chat Box
  - [x] Queue List
  - [x] Tabbed Containers
    - [x] Explore
    - [x] My Playlists
    - [x] Search Media
    - [x] Open Playlist
    - [x] Edit Playlist
    - [x] User Page
  - [x] Footer

Elements to Design and Include:
- [x] Universal Color Hex Palette (White Theme, Black Video/Chat, Teal Highlights/Contrast)
- [x] Universal Media Card divs
- [x] Universal Playlist Cards
- [x] Standard Pill Styles
- [x] Standard Button Styles
- [x] Dropdown Menus for Search, Privacy, & Add-to-Playlist
- [x] Tooltips for Icons and Buttons
- [x] Pagination Design

JS/CSS Scripting:
- [x] Draggable Media Cards in Queue and Edit-Playlist
- [x] Grabbable Media Card Darken on Hover 
- [x] Dark Overlay "Play All" on Playlist Hover
- [x] Hover Rotate Close Icon on media card
- [x] Icon Toggle Color for Hearts, Shuffle
- [x] Chatbox Load Scrolled Down
- [ ] Scrolling Chatbox "pulls" to a spinning icon
- [x] Extra classes to style "added" media cards and "user's" playlists

Things to Accomplish:
- [ ] Mobile Optimization
