### ISSUE TITLE
Backend (Task List)

### ISSUE THREAD

**Issue by rtruo001** [rtruo001/AppleTea#26]
Finish entire Backend for the App:
- [ ] Implement the MediaPlayer
  - [x] Added Youtube
  - [ ] Added Soundcloud
  - [ ] Added Vimeo
  - [ ] Added Status Bar
    - [ ] Added Play/Pause button
    - [ ] Include an input slider for seekTo()
    - [ ] Include a volume slider
  - [ ] Transition from one media player to the other
  - [ ] Update media player when Media changes
    - [x] When current media ends, gets next media from queue
    - [x] When a new media is manually selected to play
- [x] Youtube
  - [x] Can initialize Youtube player
  - [x] Initializes player from when room is entered
  - [x] Play/Pause between all Clients
  - [x] Adjust Volume
  - [x] Seek to proper time for all Clients when seekTo() is called
- [ ] Soundcloud
  - [ ] Can initialize Soundcloud player
  - [ ] Initializes player from when room is entered
  - [ ] Play/Pause between all Clients
  - [ ] Adjust Volume
  - [ ] Seek to proper time for all Clients when seekTo() is called
- [ ] Vimeo
  - [ ] Can initialize Vimeo player
  - [ ] Initializes player from when room is entered
  - [ ] Play/Pause between all Clients
  - [ ] Adjust Volume
  - [ ] Seek to proper time for all Clients when seekTo() is called
- [ ] Syncing
  - [ ] Optimize syncing
  - [ ] Fix General syncing bugs
    - [ ] When users click on play or pause multiple times in a short period of time
    - [ ] Ensure that calls made to server are only made by one Client and not all of the clients
  - [x] Able to Play all Clients 
  - [x] Able to Pause all Clients 
  - [x] Updates Queue
    - [x] When media entry is dragged
    - [x] When a new media entry is added
    - [x] When a media entry is removed
- [ ] Chat System
  - [ ] Change from Javascript/Jquery to using React
  - [x] Send messages to Server and back to all Clients
  - [x] Display when users join chat
  - [x] Display when users leave
  - [ ] Display total users in room
  - [ ] Display users currently live in room
- [ ] Queue
  - [x] Initializes queue to the server's queue
  - [x] Prevents duplicates from being added to queue
  - [ ] Add the shuffle button
  - [ ] Add the like button in queue
  - [x] Display number of added media entries
  - [ ] Display total media entries added from a playlist
  - [x] Update queue when media player requests next song
  - [x] Updates queue when dragging media entries and their positions
- [ ] Explore Tab
  - [ ] Connect to database for list of playlists
  - [ ] Create the entire algorithm and design structure for the exploration (Machine learning, playlist rankings, combination of both)
  - [ ] Display each media entries in a playlist when playlist is opened (Explore tab)
  - [ ] Able to open selected playlist to display medias (Explore tab)
- [ ] My Playlist Tab
  - [ ] Connect to database
  - [ ] Display current user's private playlists
  - [ ] Display current user's public playlists
  - [ ] Display current user's liked public playlists
  - [ ] Display each media entries in a playlist when playlist is opened (My Playlist tab)
  - [ ] Able to add selected playlist to queue (My Playlist tab)
- [ ] Selected Playlist
  - [ ] Display all media entries in current playlist
  - [ ] Media entries are draggable
  - [ ] Media Entry can be added to Queue button
  - [ ] Media Entry can be manually selected to play button
  - [ ] Media Entry can be added to a user's own playlist
- [ ] Search
  - [x] Searches with Youtube API
  - [ ] Searches Soundcloud API 
  - [ ] Searches VImeo API
  - [x] Media Entry can be added to Queue button
  - [x] Media Entry can be manually selected to play button
  - [ ] Media Entry can be added to a user's own playlist
