### ISSUE TITLE
Implement Youtube

### ISSUE THREAD

**Issue by rtruo001** [rtruo001/AppleTea#29]
- [ ] Youtube
  - [x] Can initialize Youtube player
  - [ ] Initializes player from when room is entered
  - [x] Play/Pause between all Clients
  - [x] Adjust Volume
  - [ ] Seek to proper time for all Clients when seekTo() is called
## 8/2/16
- Youtube Player is mostly done for now. 
- Needs to be initialized for when the room is entered 
- Change the Youtube player to  load the video instead of reinitializing the video everytime a media player is changed.
- Also needs to set the proper time when seekTo() is called.
