### ISSUE TITLE
Integrate Static Design into React (Checklist)

### ISSUE THREAD

**Issue by gerardliu** [rtruo001/AppleTea#71]
Static Designs designed and placed in 'AppleTea Website' folder needs to be implemented into the main code in React. We've already done a lot of this, but there will be a lot more moving forward once we create a database. For this run, we must integrate:
- [ ] Home Page
- [x] Header
  - [ ] User Profile Dropdown
- [x] Video
- [x] Chatbox
  - [ ] Chatbox Name
  - [ ] Users List
  - [ ] Add User Modal Pop Up
- [ ] Queue
- [ ] Tabs
  - [x] My Playlists
  - [ ] Playlist Cards and User Playlist Cards
  - [x] Search
  - [ ] Curator Page
  - [ ] Open Playlist
  - [ ] Edit Playlist
  - [ ] Edited Contents Must Update to Database
    Also, the numbered Navigation Controls for:
  - [ ] Queue
  - [ ] Explore
  - [ ] MyPlaylists
  - [ ] Open Playlist
